Update data acknowledgment SOP
ebi-ait/hca-ebi-wrangler-central pull request #1027
Opened 2023-01-23 12:18 UTC by idazucchi

This PR updates the instructions to run the automated import script.

Please suggest other improvements!

2023-01-23 13:40 UTC, ESapenaVentura requested changes

2023-01-23 13:40 UTC, ESapenaVentura commented on docs/SOPs/dataset_acknowledgement_SOP.md
> +        INGEST_API_TOKEN="BearerToken <dev authentication token>"
```suggestion
        INGEST_API_TOKEN="Bearer <dev authentication token>"
```

2023-01-23 13:40 UTC, ESapenaVentura commented on docs/SOPs/dataset_acknowledgement_SOP.md
> +        INGEST_API_TOKEN="BearerToken <prod authentication token>"
```suggestion
        INGEST_API_TOKEN="Bearer <prod authentication token>"
```

2023-01-23 13:40 UTC, ESapenaVentura commented on docs/SOPs/dataset_acknowledgement_SOP.md
> +   By default, the script runs against local host
```suggestion
   By default, the script runs in dry-run mode, avoiding API operations
```

2023-01-24 10:26 UTC, arschat approved these changes

2023-01-30 10:20 UTC, merged