Add HCA publication email template in the SOPs
ebi-ait/hca-ebi-wrangler-central pull request #1065
Opened 2023-03-07 10:50 UTC by arschat

Added also a no publication template by @Wkt8

Duplicate PR after accidental merge of ebi-ait/hca-ebi-wrangler-central#1060 before @ESapenaVentura review

2023-03-07 12:02 UTC, ESapenaVentura requested changes
Mostly LGTM, a comment on a specific part of the email (about archiving) and on naming of the email templates

2023-03-07 12:02 UTC, ESapenaVentura commented on docs/SOPs/contributor_communication_SOP.md
> +#### HCA branded publication - first contact
```suggestion
#### HCA branded publication - with preprint or publication
```

2023-03-07 12:02 UTC, ESapenaVentura commented on docs/SOPs/contributor_communication_SOP.md
> +[Template email](#hca-branded-publication---first-contact){: .btn .btn-blue }
```suggestion
[Template email- no preprint or publication available](#hca-branded-publication---no-preprint-or-publication){: .btn .btn-blue }
[Template email- preprint or publication available](#hca-branded-publication---with-preprint-or-publication){: .btn .btn-blue }
```

2023-03-13 11:06 UTC, idazucchi approved these changes

2023-03-14 10:24 UTC, ESapenaVentura requested changes
mostly LGTM, added a small comment on dividing a paragraph

2023-03-14 10:24 UTC, ESapenaVentura commented on docs/SOPs/contributor_communication_SOP.md
> +> If you have already archived your data in any database, could you provide us the accession number? If you would like your data to be added to the HCA DCP Data Portal, please contact us and we can s
I'd separate the 2 ideas here in 2 different paragraphs:
- First one, about asking for a pointer to the data
- Second one, offering to wrangle their data to the HCA data portal

2023-03-16 14:44 UTC, idazucchi commented on docs/SOPs/contributor_communication_SOP.md
> +> If you would like your data to be added to the HCA DCP Data Portal, please contact us and we can start the submission process. Also in that case, please inform us of any time-sensitive requirements
```suggestion
> If you would like your data to be added to the HCA DCP Data Portal, please contact us and we can start the submission process. Also in that case, please inform us of any time-sensitive requirements.
```

2023-03-16 14:44 UTC, idazucchi commented on docs/SOPs/contributor_communication_SOP.md
> +> If you would like your data to be added to the HCA DCP Data Portal, please contact us and we can start the submission process. Also in that case, please inform us of any time-sensitive requirements
If they already deposited their data in an archive there is no need for us to offer archiving. 
We are unable to archive right now anyway so there is no point in mentioning it

2023-03-16 15:08 UTC, merged