Index of SOPs & Tools
ebi-ait/hca-ebi-wrangler-central pull request #1075
Opened 2023-03-16 15:50 UTC by arschat

On #1045

# Group
Grouping of SOPs and tool documentation into content meaningful small groups.
## SOPs
* Introduction
* Triage
* Metadata spreadsheet
* Access data files
* After export
* Update schema & ontology
* Technology Types Guide
* Advanced & other SOPs
## Tools
* Download from archives
* Accessing upload area
* Useful commands
* Useful scripts

# Move
* Moved the technology types guide into SOPs folder. However, not all folders can now open in the navigation pane.
* Split `Handy_snippets.md` to multiple files, for grouping purposes, but file also exists as `All snippets`

# Change
* _config.yml added `theme:` and changed `remote_theme:` with updated just-the-docs url.
* Added small description in all navigation folders.
* Fixed table-typo in [General Best Practices](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/wrangling_best_practices.html#general-best-practices)
* Removed SOP from SOP name.
* Added links to external SOPs in the related field for reference
    - [HCA metadata structure](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md)
    - [Access terra](https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html)
    - [Contributor spreadsheet quick guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html)
    - [SpreadSheet examples](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-templates.html)
    - [hca-util](https://github.com/ebi-ait/hca-documentation/wiki/How-to-administrate-upload-areas-and-transfer-data-using-hca-util)
    - [hca-util contributor](https://ebi-ait.github.io/hca-metadata-community/contributing/uploading-data.html)
    - [Ingest programmatic submission](https://ebi-ait.github.io/ingest-programmatic-submissions/)

2023-03-20 11:00 UTC, idazucchi requested changes
The new index looks great, you've done a huge job with reorganising all the pages! The only thing that's missing is udpdating the internal links of the SOPs to reflect the new folder structure

2023-03-20 14:24 UTC, arschat reviewed
Thanks for the review, new commit fixes broken links.

2023-04-03 09:33 UTC, idazucchi approved these changes

2023-05-04 07:39 UTC, anu-shiva approved these changes

2023-05-04 14:10 UTC, ESapenaVentura approved these changes
LGTM 👍

2023-05-15 12:43 UTC, merged