New SOP - How to download data from Node
ebi-ait/hca-ebi-wrangler-central pull request #639
Opened 2022-02-15 16:50 UTC by idazucchi

These instructions are currently not available in Node, they are the result of communication with the Node support team.
They've told me that they will be integrated in the help section but there is no known deadline for that, so in the mean time I'd like to integrate these instructions in our SOPs

2022-02-18 18:21 UTC, amnonkhen commented on docs/SOPs/Node_data_how_to.md
> +- `lftp` is installed
I would add installation command or url.

2022-02-18 18:21 UTC, amnonkhen commented on docs/SOPs/Node_data_how_to.md
> +```
```suggestion
```bash
```

2022-02-18 18:21 UTC, amnonkhen commented on docs/SOPs/Node_data_how_to.md
> +```
I would add the syntax hint, for nicer formatting.
```suggestion
```bash
```

2022-02-18 18:21 UTC, amnonkhen commented on docs/SOPs/Node_data_how_to.md
> +For each project there is a folder in the format /Public/byrun/OEXX/OERXXXX/ where X is a single digit. The project folder contains a folder per run accession, each of them containing the fastq files
```suggestion
For each project there is a folder in the format `/Public/byrun/OEXX/OERXXXX/` where X is a single digit. The project folder contains a folder per run accession, each of them containing the fastq files for that run.
```

2022-02-18 18:21 UTC, amnonkhen commented on docs/SOPs/Node_data_how_to.md
> +- Node credentials: required to authenticate and connect to the ftps server
How can one obtain the credentials? Is there a link or email?

2022-02-22 10:08 UTC, Wkt8 requested changes

2022-02-22 14:16 UTC, Wkt8 approved these changes
LGTM! Good job!

2022-02-22 14:39 UTC, merged